### ISSUE TITLE
module goa.design/plugins@latest found (v2.1.3+incompatible), but does not contain package goa.design/plugins/structurizr/dsl

### ISSUE THREAD

**Issue by Taschenbergerm** [goadesign/structurizr#1]
Hi, 

I'm running the example from the readme but seemingly i have a dependency problem with the DSL 

`(base) [marvin@marvin-pc ArchAsCode]$ go run arch_as_code.go 
go: finding module for package goa.design/plugins/structurizr/dsl
go: finding module for package goa.design/goa/v3/dsl
go: downloading goa.design/goa v1.4.3
go: downloading goa.design/goa/v3 v3.1.3
go: downloading goa.design/plugins v2.1.3+incompatible
go: downloading goa.design/goa v2.1.3+incompatible
go: found goa.design/goa/v3/dsl in goa.design/goa/v3 v3.1.3
go: finding module for package goa.design/plugins/structurizr/dsl
go: downloading github.com/manveru/faker v0.0.0-20171103152722-9fbc68a78c4d
go: downloading github.com/dimfeld/httppath v0.0.0-20170720192232-ee938bf73598
go: downloading github.com/zach-klippenstein/goregen v0.0.0-20160303162051-795b5e3961ea
trth_db_loader.go:4:8: module goa.design/plugins@latest found (v2.1.3+incompatible), but does not contain package goa.design/plugins/structurizr/dsl`

go version go1.14.4 Linux/amd64

Sorry I'm relatively new to Go let me know if any more information is necessary/helpful

**Comment by Taschenbergerm** [comment]
`
package main

import . "goa.design/goa/v3/dsl"
import . "goa.design/plugins/structurizr/dsl"

var _ = Workspace("Getting Started", "This is a model of my software system.", func() {
    var System = SoftwareSystem("Software System", "My software system.")

    var User = Person("User", "A user of my software system.", func() {
        Uses(System, "Uses")
    })

    Views(func() {
        SystemContext(MySystem, "SystemContext", "An example of a System Context diagram.", func() {
            AddAll()
            AutoLayout()
        })
        Styles(func() {
            ElementStyle(System, func() {
                Background("#1168bd")
                Color("#ffffff")
             })
            ElementStyle(User, func() {
                Shape(ShapePerson)
                Background("#08427b")
                Color("#ffffff")
            })
        })
    })
})

// Executes the DSL and uploads the corresponding workspace to Structurizr.
func main() {
    // Run the model DSL
    w, err := eval.RunDSL()
    if err != nil {
        fmt.Fprintf(os.Stderr, "invalid model: %s", err.String())
        os.Exit(1)
    }

    // Upload the model to the Structurizr service. 
    // The API key and secret must be set in the STRUCTURIZR_KEY and
    // STRUCTURIZR_SECRET environment variables respectively. The 
    // workspace ID must be set in STRUCTURIZR_WORKSPACE_ID.
    var (
        key = "e5e20df4-32d6-475b-b810-3a498f31d52d"
        secret = "f3396f20-d31d-4ca0-8c70-c2ad6fc68429"
        wid = "56293"
    )
    c := service.NewClient(key, secret)
    if err := c.Put(wid, w); err != nil {
        fmt.Fprintf(os.Stderr, "failed to store workspace: %s", err.String())
    }
}`

**Comment by Taschenbergerm** [comment]
The code 

    package main
    import . "goa.design/goa/v3/dsl"
    import . "goa.design/plugins/structurizr/dsl"

    var _ = Workspace("Getting Started", "This is a model of my software system.", func() {
        var System = SoftwareSystem("Software System", "My software system.")

        var User = Person("User", "A user of my software system.", func() {
            Uses(System, "Uses")
        })

        Views(func() {
            SystemContext(MySystem, "SystemContext", "An example of a System Context diagram.", func() {
                AddAll()
                AutoLayout()
            })
            Styles(func() {
                ElementStyle(System, func() {
                    Background("#1168bd")
                    Color("#ffffff")
                 })
                ElementStyle(User, func() {
                    Shape(ShapePerson)
                    Background("#08427b")
                    Color("#ffffff")
                })
            })
        })
    })
    // Executes the DSL and uploads the corresponding workspace to Structurizr.
    func main() {
        // Run the model DSL
        w, err := eval.RunDSL()
        if err != nil {
            fmt.Fprintf(os.Stderr, "invalid model: %s", err.String())
            os.Exit(1)
        }

        // Upload the model to the Structurizr service. 
        // The API key and secret must be set in the STRUCTURIZR_KEY and
        // STRUCTURIZR_SECRET environment variables respectively. The 
        // workspace ID must be set in STRUCTURIZR_WORKSPACE_ID.
        var (
            key = <key>
            secret = <secret>
            wid = <wid>
        )
        c := service.NewClient(key, secret)
        if err := c.Put(wid, w); err != nil {
            fmt.Fprintf(os.Stderr, "failed to store workspace: %s", err.String())
        }
    }

**Comment by raphael** [comment]
There were many issues both in the example and in the code as this was a work in progress still (surprised you found this repo so quickly! :) ). Anyway the example now works.

**Comment by Taschenbergerm** [comment]
Cool i will check it out - thank you
